# setup.py
from setuptools import setup, find_packages

setup(
    name="ibkr_trading_bot",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'ib-insync',
        'python-telegram-bot',
        'fastapi',
        'uvicorn',
        'pydantic'
    ],
)